spring:
  datasource:
    url: jdbc:postgresql://droll-rabbit-5432.7tt.aws-us-east-1.cockroachlabs.cloud:26257/ponti-marriot?sslmode=verify-full&sslrootcert=src/main/resources/certificate/root.crt
    username: ponti-marriot
    password: KTiL65ieqM_OOi2aB95d3g
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://10.43.103.234:8761/eureka/}
  instance:
    prefer-ip-address: true

## Actuator configuration
management:
  endpoints:
    web:
      exposure:
        # Exposes monitoring for every endpoint
        # through /actuator/metrics
        include: "*"

  endpoint:
    health:
      # Adds an endpoint to monitor service health
      # /actuator/health
      show-details: always

  info:
    env:
      # Adds an endpoint to monitor environment info
      # /actuator/env
      enabled: true