spring:

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092


keycloak:
  login-url: http://10.43.103.234:9000/realms/myrealm/protocol/openid-connect/token
  register-url: http://10.43.103.234:9000/admin/realms/myrealm/users

server:
  port: 8088
