spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bdUsuarios?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin1234
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    function:
      definition: empleadoConsumer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        #Publishers
        sendEmpleado-out-0:
          destination: consumerNuevoEmpleado
       

keycloak:
  login-url: http://localhost:9000/realms/myrealm/protocol/openid-connect/token
  register-url: http://localhost:9000/admin/realms/myrealm/users

server:
  port: 8082
