spring:

  cloud:
    stream:
      kafka:
        binder:
          brokers: 10.43.103.234:9092
      bindings:
        # Publishers
        sendEmpleado-out-0:
          destination: consumerNuevoEmpleado
       

keycloak:
  login-url: http://10.43.103.234:9000/realms/myrealm/protocol/openid-connect/token
  register-url: http://10.43.103.234:9000/admin/realms/myrealm/users

server:
  port: 8082
